apiVersion: v1
kind: Namespace
metadata:
  name: byte-squad-namespace
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Flask-deployment
  namespace: byte-squad-namespace
  labels:
    app: Flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Flask
  template:
    metadata:
      labels:
        app: Flask
    spec:
      containers:
      - name: Flask-app
        image: jimyywang/Flask-app
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: Flask-service
  namespace: byte-squad-namespace
spec:
  type: LoadBalancer
  selector:
    app: Flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
